### PR TITLE
Restore old functionality + some new

### PR DESCRIPTION
**Pull request by digetx**
I've rebased the libdrm on the @thierryreding recent work from freedesktop.org, the old fixes still apply here and some new were added, new features were added as well (BO caching, dmabuf functions). The BO caching gives a significant performance boost to opentegra, drm_tegra_bo_to_dmabuf was tested by VDPAU driver.

### CODE REVIEW

**Comment by kusma** [comment]
I'm a bit confused... we had things like `drm_tegra_bo_from_name` before the rebase... What exactly did you do when you rebased?

**Comment by digetx** [comment]
The `drm_tegra_bo_from_name` was squashed (for some odd reason) into the old "tegra: Add missing symbols to tegra-symbol-check". For the new rebase I haven't squashed that patch, it is standalone now.

I took the https://cgit.freedesktop.org/~tagr/drm/commit/?h=staging/tegra&id=d04a12dc42e8327a6e9e4467b409364c475f4a89 and re-applied the old patches on top of it + fixed a new bug it introduced "Add missing BO list initialization" https://github.com/grate-driver/libdrm/pull/4/commits/7c608777deabb7e4100d4a3e7a1f6fd8a31259c2.

The old version used drmIoctl() that everyone else uses too. I'm not sure why @thierryreding  switched to a bare ioctl(), so I added "Use drmIoctl instead of bare ioctl" https://github.com/grate-driver/libdrm/pull/4/commits/5d827c339e0e0d7930622d6c6de8b8232855378d.

I added some new features:

https://github.com/grate-driver/libdrm/pull/4/commits/7f3cce3cf6f38a7b38efd1d133d61786a5b36d68 Propagate error from drm_tegra_bo_unref()
https://github.com/grate-driver/libdrm/pull/4/commits/6f9b47ae5f9f8ca016dabe118094afbcb6303601 Prepare pushbuf in drm_tegra_pushbuf_relocate
https://github.com/grate-driver/libdrm/pull/4/commits/d044b90e376e646225fc9ac32d0a02e6fc0474c7 Implement BO caching
https://github.com/grate-driver/libdrm/pull/4/commits/4323703375d34a6258353d5a51e9ae51967c6b4b Add dmabuf from/to helpers to API

**Comment by kusma** [comment]
@digetx: So, you didn't force-push the rebased stuff, you force-pushed @thierryreding's stuff, and added back things here? I'd prefer to be able to pull the new features (BO-caching etc) separately, in case of regressions in some use-cases...

**Comment by digetx** [comment]
Yes, I only force-pushed that one patch. I thought it would cleaner to review that way, you have already spotted the `drm_tegra_bo_from_name` :) I'll push the old patches now, leaving new patches for review.

**Comment by digetx** [comment]
Pushed ;)

**Pull request merged**
