### PR TITLE
Add valgrind deps for tegra/meson.build

### PR DESCRIPTION
**Pull request by kwizart**
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

### CODE REVIEW

**Comment by kwizart** [comment]
FYI, I haven't managed to build the libdrm_tegra library. It fails at:
---
[58/133] cc  -o tegra/libdrm_tegra.so.0.0.0 'tegra/drm_tegra@sha/tegra.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libdrm_tegra.so.0 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld libdrm.so.2.4.0 -Wl,--end-group '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/  
FAILED: tegra/libdrm_tegra.so.0.0.0 
cc  -o tegra/libdrm_tegra.so.0.0.0 'tegra/drm_tegra@sha/tegra.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libdrm_tegra.so.0 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld libdrm.so.2.4.0 -Wl,--end-group '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/  
tegra/drm_tegra@sha/tegra.c.o: In function `drm_tegra_wrap':
/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/../tegra/tegra.c:289: undefined reference to `drm_tegra_bo_cache_init'
tegra/drm_tegra@sha/tegra.c.o: In function `drm_tegra_close':
/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/../tegra/tegra.c:329: undefined reference to `drm_tegra_bo_cache_cleanup'
tegra/drm_tegra@sha/tegra.c.o: In function `drm_tegra_bo_unref':
/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/../tegra/tegra.c:485: undefined reference to `drm_tegra_bo_cache_free'
tegra/drm_tegra@sha/tegra.c.o: In function `__drm_tegra_bo_map':
/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/../tegra/tegra.c:510: undefined reference to `drm_tegra_bo_cache_map'
tegra/drm_tegra@sha/tegra.c.o: In function `drm_tegra_bo_new':
/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/../tegra/tegra.c:349: undefined reference to `drm_tegra_bo_cache_alloc'
tegra/drm_tegra@sha/tegra.c.o: In function `drm_tegra_bo_unmap':
/builddir/build/BUILD/libdrm-2.4.91/armv7hl-redhat-linux-gnueabi/../tegra/tegra.c:610: undefined reference to `drm_tegra_bo_cache_unmap'
---

Since I've rebased the current grate/libdrm on current master, there is an additional library as dep_atomic_ops

**Comment by digetx** [comment]
@kwizart Nicolas, thank you very much! As you probably noticed, libdrm was rebased on a recent upstream, but I haven't touched `meson.build` at all, so it misses `*.c` files. Adding missing source files to `meson.build` should fix compilation using meson.

This patch is fine to me. Though, do you know if this means that with meson valgrind dependency would be mandatory?

**Comment by kwizart** [comment]
>This patch is fine to me. Though, do you know if this means that with meson valgrind dependency would be mandatory?
I've copied this change from the intel driver, so the same should apply to intel. I haven't looked at how the depdency is implemented yet...

**Comment by digetx** [comment]
I've seen that this replicates what others are doing, just thought maybe you know. I'll apply this patch now, thank you!

**Pull request merged**
